{
 "title": "Owon PSU metrics dashboard",
 "tags": [ "owonpsu" ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "psu_measured_current", "legendFormat": "OWON PSU ({{device}})" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "psu_measured_voltage", "legendFormat": "OWON PSU ({{device}})" }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "psu_device_info", "legendFormat": "{{manufacturer}} {{model}}" }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "psu_device_info", "legendFormat": "{{firmware_version}}" }
   ]
  },
  {
   "title": "Serial number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "psu_device_info", "legendFormat": "{{serial_num}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "psu_measured_voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "psu_measured_current", "legendFormat": "__auto" }
   ]
  }
 ]
}